class Development:
    DEBUG = True
    SECRET_KEY = "Very sec"
    SQLALCHEMY_DATABASE_URI = "sqlite:///data.sqlite"
    SQLALCHEMY_TRACK_MODIFICATIONS = False
   
    # SQLALCHEMY_COMMIT_ON_TEARDOWN = True
    # SQLALCHEMY_RECORD_QUERIES = True
    # SQLALCHEMY_POOL_SIZE = 10
    # SQLALCHEMY_MAX_OVERFLOW = 20
    # SQLALCHEMY_POOL_TIMEOUT = 10
    # SQLALCHEMY_POOL_RECYCLE = 20


class Testing:
    DEBUG = True
    SECRET_KEY = "Very sec"
    SQLALCHEMY_DATABASE_URI = "sqlite:///test.sqlite"
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SEVER_NAME = "localhost:5000"
    # SQLALCHEMY_COMMIT_ON_TEARDOWN = True
    # SQLALCHEMY_RECORD_QUERIES = True
    # SQLALCHEMY_POOL_SIZE = 10
    # SQLALCHEMY_MAX_OVERFLOW = 20
    # SQLALCHEMY_POOL_TIMEOUT = 10
    # SQLALCHEMY_POOL_RECYCLE = 20
